config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")  # rake routes --> to know with routes are available to us
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        #format.json { render :show, status: :created, location: #@blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        #format.json { render json: @blog.errors, status: #:unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        #format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        #format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      #format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= blog.body %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="blogs-title">Blogs</h1>
 <div class="content">
  <% @blogs.each do |blog| %>
    <%= render blog %>
    <p>
      <%= link_to "Show this blog", blog %>
    </p>
  <% end %>
 </div>
   <div class="new-blog">
      <%= link_to "New blog", new_blog_path %>
   </div>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevcampPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>